### ISSUE TITLE
node 14 no longer supported

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#1367]
### Background Information

**Package Version(s)**:

instructure-ui@8.48.0

### Describe the Bug

The `package.json` list the minimum version as 14, attempting to run various commands fails:
```
❯ npm run bootstrap

> instructure-ui@8.48.0 bootstrap /Users/buckett/Developer/instructure-ui
> node scripts/bootstrap.js

cleaning packages...
clean finished
/Users/buckett/Developer/instructure-ui/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:73
                    projectNodes[node].name ??= node;
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/buckett/Developer/instructure-ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:9:39)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
child_process.js:866
    throw err;
    ^

Error: Command failed: lerna run prepare-build --stream --scope @instructure/ui-icons
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at buildProject (/Users/buckett/Developer/instructure-ui/scripts/bootstrap.js:36:3)
    at bootstrap (/Users/buckett/Developer/instructure-ui/scripts/bootstrap.js:82:3)
    at Object.<anonymous> (/Users/buckett/Developer/instructure-ui/scripts/bootstrap.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25811,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! instructure-ui@8.48.0 bootstrap: `node scripts/bootstrap.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the instructure-ui@8.48.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**

Low

**Comment by buckett** [comment]
I think it's `lerna` that's pulling in `nx`:
```
❯ npm ls nx
instructure-ui@8.48.0 /Users/buckett/Developer/instructure-ui
└─┬ lerna@7.4.1
  ├─┬ @lerna/create@7.4.1
  │ └── nx@16.10.0 deduped
  ├─┬ @nx/devkit@16.10.0
  │ └── nx@16.10.0 deduped
  └─┬ nx@16.10.0
    └─┬ @nrwl/tao@16.10.0
      └── nx@16.10.0 deduped
```

https://nx.dev/nx-api/workspace/documents/nx-nodejs-typescript-version-matrix - says that node 16 is needed for nx 16.

I'm guessing it's better to say the minimum version is now 16?
