### ISSUE TITLE
instui codemod blows up

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#76]
I was trying to use codemod to update some changes, but when running against a few files with just `instui codemod` I got stack traces every time it tried to fix a file:
```
 ERR /Users/buckett/Documents/oxford/canvas-signup/canvas-signup-frontend/src/student/StudentEvent.js Transformation error (/Users/buckett/.nvm/versions/node/v12.4.0/lib/node_modules/@instructure/instui-cli/node_modules/@instructure/instui-config/codemod-configs/v7/propNames.config.json: Unexpected token ] in JSON at position 2472)
SyntaxError: /Users/buckett/.nvm/versions/node/v12.4.0/lib/node_modules/@instructure/instui-cli/node_modules/@instructure/instui-config/codemod-configs/v7/propNames.config.json: Unexpected token ] in JSON at position 2472
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:799:27)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at require (/Users/buckett/.nvm/versions/node/v12.4.0/lib/node_modules/@instructure/instui-cli/node_modules/@instructure/ui-codemods/lib/utils/requireUncached.js:26:10)
    at requireUncached (/Users/buckett/.nvm/versions/node/v12.4.0/lib/node_modules/@instructure/instui-cli/node_modules/@instructure/ui-codemods/lib/updatePropNames.js:34:37)
```
Looking in the `propNames.config.json` I see this chunk:
```
  "Popover": {
    "7.0.0": [
      { "old": "show", "new": "isShowingContent" },
      { "old": "label", "new": "screenReaderLabel" },
      { "old": "alignArrow", "new": "shouldAlignArrow" },
      { "old": "trackPosition", "new": "shouldTrackPosition" },
      { "old": "defaultShow", "new": "defaultIsShowingContent" },
      { "old": "onShow", "new": "onRequestShowContent" },
      { "old": "onDismiss", "new": "onRequestHideContent" },
      { "old": "variant", "new": "color", "values": [
        { "old": "default", "new": "primary" },
        { "old": "inverse", "new": "primary-inverse" }
      ]},
    ]
  },
```
I think it's blowing up on the trailing `,` in the array values (`]},` should be `]}`)

**Comment by serikjensen** [comment]
@buckett you are spot on! I just pushed a patch and it will be available in the next release. Thank you for surfacing this.

**Comment by buckett** [comment]
@serikjensen No probs, thanks for the quick fix.

**Comment by serikjensen** [comment]
https://github.com/instructure/instructure-ui/commit/81f19752e938521fe5836d0583eef27c1284c19f
