### ISSUE TITLE
ReferenceError: ResizeObserver is not defined

### ISSUE THREAD

**Issue by semihucari** [instructure/instructure-ui#808]
### Background Information

**Package Version(s)**:
"@instructure/ui": "8.11.1"

**Browser**:
Chrome latest

**Component**:
Modal

### Describe the Bug
When I run a unit test to render a modal, I get the following error, is this expected or do you know a workaround for this?

```
ReferenceError: ResizeObserver is not defined

      54 |
      55 | test("renders product with details", () => {
    > 56 |   render(<EmotionThemeProvider theme={canvas}><ProductDetailsModal {...props} /></EmotionThemeProvider>);
         |   ^
      57 |   const brandText = screen.getByText(testProduct.brand);
      58 |   expect(brandText).toBeInTheDocument();
      59 | });

      at TestableComponent.componentDidMount (node_modules/@instructure/ui-truncate-text/lib/TruncateText/index.js:88:34)
      at TestableComponent.componentDidMount (node_modules/@instructure/ui-react-utils/lib/hack.js:65:15)
      at TestableComponent.componentDidMount (node_modules/@instructure/ui-testable/lib/testable.js:57:15)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20663:24)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23151:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at Object.<anonymous>.test (src/test/modal.test.tsx:56:3)

  console.error
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports (/home/developer/seg/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLCanvasElementImpl.getContext (/home/developer/seg/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
        at HTMLCanvasElement.getContext (/home/developer/seg/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
        at measure (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:60:26)
        at measureText (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:49:14)
        at Truncator.setup (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:145:47)
        at new Truncator (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:106:10)
        at truncate (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:71:21)
        at TestableComponent.truncate (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/index.js:179:44)
        at TestableComponent.componentDidMount (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/index.js:79:12) undefined
```

**Comment by semihucari** [comment]
Hi;

I mocked the window ResizeObjserver

class ResizeObserver {
  disconnect() {}
  observe() {}
  unobserve() {}
}

window.ResizeObserver = ResizeObserver;

but now I get this error 

console.error
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports (/home/developer/seg/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLCanvasElementImpl.getContext (/home/developer/seg/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
        at HTMLCanvasElement.getContext (/home/developer/seg/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
        at measure (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:60:26)
        at measureText (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:49:14)
        at Truncator.setup (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:145:47)
        at new Truncator (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:106:10)
        at truncate (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/truncate.js:71:21)
        at TestableComponent.truncate (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/index.js:179:44)
        at TestableComponent.componentDidMount (/home/developer/seg/node_modules/@instructure/ui-truncate-text/lib/TruncateText/index.js:79:12) undefined

      at VirtualConsole.on.e (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
      at HTMLCanvasElementImpl.getContext (node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
      at HTMLCanvasElement.getContext (node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
      at measure (node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:60:26)
      at measureText (node_modules/@instructure/ui-truncate-text/lib/TruncateText/utils/measureText.js:49:14)

**Comment by matyasf** [comment]
hi!

These errors pop up because you are using `Jest` to test, and as I see from the errors some DOM APIs are not mocked out. You can mock stuff out manually (like you did with `ResizeObserver`) like you did, the second error message complains about this like not working in Jest: https://github.com/davidtheclark/no-scroll/blob/master/index.js#L44

**Comment by matyasf** [comment]
Does the answer above solve your problem?

**Comment by semihucari** [comment]
I'm still not sure, It's the first time I get these errors while unit testing, so I thought maybe it's related to your UI library
